export const mockData = {
  nodes: [
    {
      id: 'Darwin Chang',
      weight: 16,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Marc Schumann',
      weight: 0,
      group: 2,
      cat: 'astro-ph.IM',
      cat_name: 'Instrumentation and Methods for Astrophysics',
    },
    {
      id: 'Laura Baudis',
      weight: 0,
      group: 2,
      cat: 'astro-ph.IM',
      cat_name: 'Instrumentation and Methods for Astrophysics',
    },
    {
      id: 'W. -Y. Keung',
      weight: 1,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Ernest Ma',
      weight: 1,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'A. Zee',
      weight: 1,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'R. N. Mohapatra',
      weight: 1,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Darwin Bautista',
      weight: 1,
      group: 3,
      cat: 'cs.LG',
      cat_name: 'Learning',
    },
    {
      id: 'Raimarc Dionido',
      weight: 1,
      group: 3,
      cat: 'cs.LG',
      cat_name: 'Learning',
    },
    {
      id: 'Oscar Darwin',
      weight: 1,
      group: 4,
      cat: 'cs.LO',
      cat_name: 'Logic in Computer Science',
    },
    {
      id: 'Stefan Kiefer',
      weight: 1,
      group: 4,
      cat: 'cs.LO',
      cat_name: 'Logic in Computer Science',
    },
    {
      id: 'Mladen Georgiev',
      weight: 1,
      group: 5,
      cat: 'physics.ao-ph',
      cat_name: 'Atmospheric and Oceanic Physics',
    },
    {
      id: 'Jai Singh',
      weight: 1,
      group: 5,
      cat: 'physics.ao-ph',
      cat_name: 'Atmospheric and Oceanic Physics',
    },
    {
      id: 'Dung-Hai Lee',
      weight: 1,
      group: 6,
      cat: 'cond-mat.str-el',
      cat_name: 'Strongly Correlated Electrons',
    },
    {
      id: 'Wai-Yee Keung',
      weight: 4,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Ivan Phillips',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Jiang Liu',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Palash B. Pal',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Palash Pal',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Xiao-Gang He',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Sandip Pakvasa',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Shih-Chang Lee',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Paul Turcotte',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'Chuan-Hung Chen',
      weight: 1,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
    {
      id: 'David Bowser-Chao',
      weight: 2,
      group: 1,
      cat: 'hep-ph',
      cat_name: 'High Energy Physics - Phenomenology',
    },
  ],
  links: [
    { source: 'Darwin Chang', target: 'W. -Y. Keung' },
    { source: 'Darwin Chang', target: 'Ernest Ma' },
    { source: 'Darwin Chang', target: 'A. Zee' },
    { source: 'Darwin Chang', target: 'R. N. Mohapatra' },
    { source: 'Darwin Chang', target: 'Dung-Hai Lee' },
    { source: 'Darwin Chang', target: 'Wai-Yee Keung' },
    { source: 'Darwin Chang', target: 'Ivan Phillips' },
    { source: 'Darwin Chang', target: 'Jiang Liu' },
    { source: 'Darwin Chang', target: 'Palash B. Pal' },
    { source: 'Darwin Chang', target: 'Palash Pal' },
    { source: 'Darwin Chang', target: 'Xiao-Gang He' },
    { source: 'Darwin Chang', target: 'Sandip Pakvasa' },
    { source: 'Darwin Chang', target: 'Shih-Chang Lee' },
    { source: 'Darwin Chang', target: 'Paul Turcotte' },
    { source: 'Darwin Chang', target: 'Chuan-Hung Chen' },
    { source: 'Darwin Chang', target: 'David Bowser-Chao' },
    { source: 'Darwin Bautista', target: 'Raimarc Dionido' },
    { source: 'Oscar Darwin', target: 'Stefan Kiefer' },
    { source: 'Mladen Georgiev', target: 'Jai Singh' },
    { source: 'Wai-Yee Keung', target: 'Ivan Phillips' },
    { source: 'Wai-Yee Keung', target: 'Palash Pal' },
    { source: 'Wai-Yee Keung', target: 'David Bowser-Chao' },
    { source: 'Jiang Liu', target: 'Palash B. Pal' },
    { source: 'Xiao-Gang He', target: 'Sandip Pakvasa' },
    { source: 'Shih-Chang Lee', target: 'Paul Turcotte' },
  ],
};
