export const test_data = {
  nodes: [
    { id: 'Dexter Kozen', val: '1' },
    { id: 'Nicholas Ruozzi' },
    { id: 'Matvey Soloviev' },
    { id: 'Zoltan Esik' },
    { id: 'Fredrik Dahlqvist' },
    { id: 'Lutz Schröder' },
    { id: 'Stefan Milius' },
    { id: 'Thorsten Wißmann' },
    { id: 'Steffen Smolka' },
    { id: 'Praveen Kumar' },
    { id: 'Nate Foster' },
    { id: 'Alexandra Silva' },
    { id: 'Niels Bjørn Bugge Grathwohl' },
    { id: 'Fritz Henglein' },
    { id: 'Justin Hsu' },
    { id: 'David Kahn' },
    { id: 'Tobias Kappé' },
    { id: 'David M Kahn' },
    { id: 'Nick Bezhanishvili', val: '1' },
    { id: 'Marcello Bonsangue' },
    { id: 'Helle Hvid Hansen', val: '1' },
    { id: 'Clemens Kupke' },
    { id: 'Prakash Panangaden' },
  ],
  links: [
    { source: 'Dexter Kozen', target: 'Nicholas Ruozzi' },
    { source: 'Dexter Kozen', target: 'Matvey Soloviev' },
    { source: 'Dexter Kozen', target: 'Stefan Milius' },
    { source: 'Dexter Kozen', target: 'Thorsten Wißmann' },
    { source: 'Dexter Kozen', target: 'Alexandra Silva' },
    { source: 'Dexter Kozen', target: 'Clemens Kupke' },
    { source: 'Dexter Kozen', target: 'Prakash Panangaden' },
    { source: 'Zoltan Esik', target: 'Dexter Kozen' },
    { source: 'Fredrik Dahlqvist', target: 'Dexter Kozen' },
    { source: 'Lutz Schröder', target: 'Dexter Kozen' },
    { source: 'Lutz Schröder', target: 'Stefan Milius' },
    { source: 'Lutz Schröder', target: 'Thorsten Wißmann' },
    { source: 'Stefan Milius', target: 'Thorsten Wißmann' },
    { source: 'Steffen Smolka', target: 'Praveen Kumar' },
    { source: 'Steffen Smolka', target: 'Nate Foster' },
    { source: 'Steffen Smolka', target: 'Dexter Kozen' },
    { source: 'Steffen Smolka', target: 'Alexandra Silva' },
    { source: 'Steffen Smolka', target: 'Justin Hsu' },
    { source: 'Steffen Smolka', target: 'David Kahn' },
    { source: 'Steffen Smolka', target: 'Tobias Kappé' },
    { source: 'Steffen Smolka', target: 'David M Kahn' },
    { source: 'Praveen Kumar', target: 'Nate Foster' },
    { source: 'Praveen Kumar', target: 'Dexter Kozen' },
    { source: 'Praveen Kumar', target: 'Alexandra Silva' },
    { source: 'Praveen Kumar', target: 'Justin Hsu' },
    { source: 'Praveen Kumar', target: 'David Kahn' },
    { source: 'Praveen Kumar', target: 'David M Kahn' },
    { source: 'Nate Foster', target: 'Dexter Kozen' },
    { source: 'Nate Foster', target: 'Alexandra Silva' },
    { source: 'Nate Foster', target: 'Justin Hsu' },
    { source: 'Nate Foster', target: 'David Kahn' },
    { source: 'Nate Foster', target: 'Tobias Kappé' },
    { source: 'Niels Bjørn Bugge Grathwohl', target: 'Fritz Henglein' },
    { source: 'Niels Bjørn Bugge Grathwohl', target: 'Dexter Kozen' },
    { source: 'Fritz Henglein', target: 'Dexter Kozen' },
    { source: 'Justin Hsu', target: 'David Kahn' },
    { source: 'Justin Hsu', target: 'Dexter Kozen' },
    { source: 'Justin Hsu', target: 'Alexandra Silva' },
    { source: 'Justin Hsu', target: 'Tobias Kappé' },
    { source: 'David Kahn', target: 'Dexter Kozen' },
    { source: 'David Kahn', target: 'Alexandra Silva' },
    { source: 'Tobias Kappé', target: 'Dexter Kozen' },
    { source: 'Tobias Kappé', target: 'Alexandra Silva' },
    { source: 'David M Kahn', target: 'Nate Foster' },
    { source: 'David M Kahn', target: 'Justin Hsu' },
    { source: 'David M Kahn', target: 'Dexter Kozen' },
    { source: 'David M Kahn', target: 'Alexandra Silva' },
    { source: 'Nick Bezhanishvili', target: 'Marcello Bonsangue' },
    { source: 'Nick Bezhanishvili', target: 'Helle Hvid Hansen' },
    { source: 'Nick Bezhanishvili', target: 'Dexter Kozen' },
    { source: 'Nick Bezhanishvili', target: 'Clemens Kupke' },
    { source: 'Nick Bezhanishvili', target: 'Prakash Panangaden' },
    { source: 'Nick Bezhanishvili', target: 'Alexandra Silva' },
    { source: 'Marcello Bonsangue', target: 'Helle Hvid Hansen' },
    { source: 'Marcello Bonsangue', target: 'Dexter Kozen' },
    { source: 'Marcello Bonsangue', target: 'Clemens Kupke' },
    { source: 'Marcello Bonsangue', target: 'Prakash Panangaden' },
    { source: 'Marcello Bonsangue', target: 'Alexandra Silva' },
    { source: 'Helle Hvid Hansen', target: 'Dexter Kozen' },
    { source: 'Helle Hvid Hansen', target: 'Clemens Kupke' },
    { source: 'Helle Hvid Hansen', target: 'Prakash Panangaden' },
    { source: 'Helle Hvid Hansen', target: 'Alexandra Silva' },
    { source: 'Clemens Kupke', target: 'Prakash Panangaden' },
    { source: 'Clemens Kupke', target: 'Alexandra Silva' },
    { source: 'Prakash Panangaden', target: 'Alexandra Silva' },
  ],
};
