export const testdata = {
  nodes: [
    { id: 'D. L. Khokhlov' },
    { id: 'Raimo Vuopionperä' },
    { id: 'Yang Yang' },
    { id: 'Kurt R. Brorsen' },
    { id: 'Tanner Culpitt' },
    { id: 'Michael V. Pak' },
    { id: 'Sharon Hammes-Schiffer' },
    { id: 'Gilberto M. Kremer' },
    { id: 'Anatoly Yu. Smirnov' },
    { id: "Sergey E. Savel'ev" },
    { id: 'Franco Nori' },
    { id: 'Narges Ahmadi' },
    { id: 'Kai Germaschewski' },
    { id: 'Joachim Raeder' },
    { id: 'T. Lappi' },
    { id: 'H. Mäntysaari' },
    { id: ' Fayyazuddin' },
  ],
  links: [
    { source: 'Yang Yang', target: 'Kurt R. Brorsen' },
    { source: 'Yang Yang', target: 'Tanner Culpitt' },
    { source: 'Yang Yang', target: 'Michael V. Pak' },
    { source: 'Yang Yang', target: 'Sharon Hammes-Schiffer' },
    { source: 'Kurt R. Brorsen', target: 'Tanner Culpitt' },
    { source: 'Kurt R. Brorsen', target: 'Michael V. Pak' },
    { source: 'Kurt R. Brorsen', target: 'Sharon Hammes-Schiffer' },
    { source: 'Tanner Culpitt', target: 'Michael V. Pak' },
    { source: 'Tanner Culpitt', target: 'Sharon Hammes-Schiffer' },
    { source: 'Michael V. Pak', target: 'Sharon Hammes-Schiffer' },
    { source: 'Anatoly Yu. Smirnov', target: "Sergey E. Savel'ev" },
    { source: 'Anatoly Yu. Smirnov', target: 'Franco Nori' },
    { source: "Sergey E. Savel'ev", target: 'Franco Nori' },
    { source: 'Narges Ahmadi', target: 'Kai Germaschewski' },
    { source: 'Narges Ahmadi', target: 'Joachim Raeder' },
    { source: 'Kai Germaschewski', target: 'Joachim Raeder' },
    { source: 'T. Lappi', target: 'H. Mäntysaari' },
    { source: 'Anatoly Yu. Smirnov', target: "Sergey E. Savel'ev" },
    { source: 'Anatoly Yu. Smirnov', target: 'Franco Nori' },
    { source: "Sergey E. Savel'ev", target: 'Franco Nori' },
  ],
};
