export const test_data = {
  nodes: [
    { id: 'Dexter Kozen', weight: 22 },
    { id: 'Nicholas Ruozzi', weight: 1 },
    { id: 'Zoltan Esik', weight: 1 },
    { id: 'Matvey Soloviev', weight: 1 },
    { id: 'Fredrik Dahlqvist', weight: 1 },
    { id: 'Lutz Schröder', weight: 3 },
    { id: 'Stefan Milius', weight: 3 },
    { id: 'Thorsten Wißmann', weight: 3 },
    { id: 'Steffen Smolka', weight: 8 },
    { id: 'Praveen Kumar', weight: 7 },
    { id: 'Nate Foster', weight: 8 },
    { id: 'Alexandra Silva', weight: 13 },
    { id: 'Niels Bjørn Bugge Grathwohl', weight: 2 },
    { id: 'Fritz Henglein', weight: 2 },
    { id: 'Justin Hsu', weight: 8 },
    { id: 'David Kahn', weight: 6 },
    { id: 'Tobias Kappé', weight: 5 },
    { id: 'David M Kahn', weight: 6 },
    { id: 'Nick Bezhanishvili', weight: 6 },
    { id: 'Marcello Bonsangue', weight: 6 },
    { id: 'Helle Hvid Hansen', weight: 6 },
    { id: 'Clemens Kupke', weight: 6 },
    { id: 'Prakash Panangaden', weight: 6 },
  ],
  links: [
    { source: 'Dexter Kozen', target: 'Nicholas Ruozzi' },
    { source: 'Dexter Kozen', target: 'Zoltan Esik' },
    { source: 'Dexter Kozen', target: 'Matvey Soloviev' },
    { source: 'Dexter Kozen', target: 'Fredrik Dahlqvist' },
    { source: 'Dexter Kozen', target: 'Lutz Schröder' },
    { source: 'Dexter Kozen', target: 'Stefan Milius' },
    { source: 'Dexter Kozen', target: 'Thorsten Wißmann' },
    { source: 'Dexter Kozen', target: 'Steffen Smolka' },
    { source: 'Dexter Kozen', target: 'Praveen Kumar' },
    { source: 'Dexter Kozen', target: 'Nate Foster' },
    { source: 'Dexter Kozen', target: 'Alexandra Silva' },
    { source: 'Dexter Kozen', target: 'Niels Bjørn Bugge Grathwohl' },
    { source: 'Dexter Kozen', target: 'Fritz Henglein' },
    { source: 'Dexter Kozen', target: 'Justin Hsu' },
    { source: 'Dexter Kozen', target: 'David Kahn' },
    { source: 'Dexter Kozen', target: 'Tobias Kappé' },
    { source: 'Dexter Kozen', target: 'David M Kahn' },
    { source: 'Dexter Kozen', target: 'Nick Bezhanishvili' },
    { source: 'Dexter Kozen', target: 'Marcello Bonsangue' },
    { source: 'Dexter Kozen', target: 'Helle Hvid Hansen' },
    { source: 'Dexter Kozen', target: 'Clemens Kupke' },
    { source: 'Dexter Kozen', target: 'Prakash Panangaden' },
    { source: 'Lutz Schröder', target: 'Stefan Milius' },
    { source: 'Lutz Schröder', target: 'Thorsten Wißmann' },
    { source: 'Stefan Milius', target: 'Thorsten Wißmann' },
    { source: 'Steffen Smolka', target: 'Praveen Kumar' },
    { source: 'Steffen Smolka', target: 'Nate Foster' },
    { source: 'Steffen Smolka', target: 'Alexandra Silva' },
    { source: 'Steffen Smolka', target: 'Justin Hsu' },
    { source: 'Steffen Smolka', target: 'David Kahn' },
    { source: 'Steffen Smolka', target: 'Tobias Kappé' },
    { source: 'Steffen Smolka', target: 'David M Kahn' },
    { source: 'Praveen Kumar', target: 'Nate Foster' },
    { source: 'Praveen Kumar', target: 'Alexandra Silva' },
    { source: 'Praveen Kumar', target: 'Justin Hsu' },
    { source: 'Praveen Kumar', target: 'David Kahn' },
    { source: 'Praveen Kumar', target: 'David M Kahn' },
    { source: 'Nate Foster', target: 'Alexandra Silva' },
    { source: 'Nate Foster', target: 'Justin Hsu' },
    { source: 'Nate Foster', target: 'David Kahn' },
    { source: 'Nate Foster', target: 'Tobias Kappé' },
    { source: 'Nate Foster', target: 'David M Kahn' },
    { source: 'Alexandra Silva', target: 'Justin Hsu' },
    { source: 'Alexandra Silva', target: 'David Kahn' },
    { source: 'Alexandra Silva', target: 'Tobias Kappé' },
    { source: 'Alexandra Silva', target: 'David M Kahn' },
    { source: 'Alexandra Silva', target: 'Nick Bezhanishvili' },
    { source: 'Alexandra Silva', target: 'Marcello Bonsangue' },
    { source: 'Alexandra Silva', target: 'Helle Hvid Hansen' },
    { source: 'Alexandra Silva', target: 'Clemens Kupke' },
    { source: 'Alexandra Silva', target: 'Prakash Panangaden' },
    { source: 'Niels Bjørn Bugge Grathwohl', target: 'Fritz Henglein' },
    { source: 'Justin Hsu', target: 'David Kahn' },
    { source: 'Justin Hsu', target: 'Tobias Kappé' },
    { source: 'Justin Hsu', target: 'David M Kahn' },
    { source: 'Nick Bezhanishvili', target: 'Marcello Bonsangue' },
    { source: 'Nick Bezhanishvili', target: 'Helle Hvid Hansen' },
    { source: 'Nick Bezhanishvili', target: 'Clemens Kupke' },
    { source: 'Nick Bezhanishvili', target: 'Prakash Panangaden' },
    { source: 'Marcello Bonsangue', target: 'Helle Hvid Hansen' },
    { source: 'Marcello Bonsangue', target: 'Clemens Kupke' },
    { source: 'Marcello Bonsangue', target: 'Prakash Panangaden' },
    { source: 'Helle Hvid Hansen', target: 'Clemens Kupke' },
    { source: 'Helle Hvid Hansen', target: 'Prakash Panangaden' },
    { source: 'Clemens Kupke', target: 'Prakash Panangaden' },
  ],
};
