export const update_data = {
  nodes: [
    { id: 'Helle Hvid Hansen', val: 2 },
    { id: 'Clemens Kupke' },
    { id: 'Jan Rutten' },
    { id: 'Eric Pacuit' },
    { id: 'Johannes Marti' },
    { id: 'Yde Venema' },
    { id: 'Jim de Groot' },
    { id: 'Alexander Kurz' },
    { id: 'Joerg Endrullis' },
    { id: 'Dimitri Hendriks' },
    { id: 'Andrew Polonsky' },
    { id: 'Alexandra Silva' },
    { id: 'Jörg Endrullis' },
    { id: 'Sebastian Enqvist' },
    { id: 'Frank M. V. Feys' },
    { id: 'Marcello M. Bonsangue' },
    { id: 'Jurriaan Rot' },
    { id: 'Nick Bezhanishvili' },
    { id: 'Marcello Bonsangue' },
    { id: 'Dexter Kozen', val: 2 },
    { id: 'Prakash Panangaden' },
  ],
  links: [
    { source: 'Helle Hvid Hansen', target: 'Clemens Kupke' },
    { source: 'Helle Hvid Hansen', target: 'Jan Rutten' },
    { source: 'Helle Hvid Hansen', target: 'Eric Pacuit' },
    { source: 'Helle Hvid Hansen', target: 'Johannes Marti' },
    { source: 'Helle Hvid Hansen', target: 'Yde Venema' },
    { source: 'Helle Hvid Hansen', target: 'Alexander Kurz' },
    { source: 'Helle Hvid Hansen', target: 'Dimitri Hendriks' },
    { source: 'Helle Hvid Hansen', target: 'Andrew Polonsky' },
    { source: 'Helle Hvid Hansen', target: 'Alexandra Silva' },
    { source: 'Helle Hvid Hansen', target: 'Jurriaan Rot' },
    { source: 'Helle Hvid Hansen', target: 'Dexter Kozen' },
    { source: 'Helle Hvid Hansen', target: 'Prakash Panangaden' },
    { source: 'Clemens Kupke', target: 'Jan Rutten' },
    { source: 'Clemens Kupke', target: 'Eric Pacuit' },
    { source: 'Clemens Kupke', target: 'Johannes Marti' },
    { source: 'Clemens Kupke', target: 'Yde Venema' },
    { source: 'Clemens Kupke', target: 'Prakash Panangaden' },
    { source: 'Clemens Kupke', target: 'Alexandra Silva' },
    { source: 'Johannes Marti', target: 'Yde Venema' },
    { source: 'Jim de Groot', target: 'Helle Hvid Hansen' },
    { source: 'Jim de Groot', target: 'Alexander Kurz' },
    { source: 'Joerg Endrullis', target: 'Helle Hvid Hansen' },
    { source: 'Joerg Endrullis', target: 'Dimitri Hendriks' },
    { source: 'Joerg Endrullis', target: 'Andrew Polonsky' },
    { source: 'Joerg Endrullis', target: 'Alexandra Silva' },
    { source: 'Dimitri Hendriks', target: 'Andrew Polonsky' },
    { source: 'Dimitri Hendriks', target: 'Alexandra Silva' },
    { source: 'Andrew Polonsky', target: 'Alexandra Silva' },
    { source: 'Jörg Endrullis', target: 'Helle Hvid Hansen' },
    { source: 'Jörg Endrullis', target: 'Dimitri Hendriks' },
    { source: 'Jörg Endrullis', target: 'Andrew Polonsky' },
    { source: 'Jörg Endrullis', target: 'Alexandra Silva' },
    { source: 'Sebastian Enqvist', target: 'Helle Hvid Hansen' },
    { source: 'Sebastian Enqvist', target: 'Clemens Kupke' },
    { source: 'Sebastian Enqvist', target: 'Johannes Marti' },
    { source: 'Sebastian Enqvist', target: 'Yde Venema' },
    { source: 'Frank M. V. Feys', target: 'Helle Hvid Hansen' },
    { source: 'Marcello M. Bonsangue', target: 'Helle Hvid Hansen' },
    { source: 'Marcello M. Bonsangue', target: 'Alexander Kurz' },
    { source: 'Marcello M. Bonsangue', target: 'Jurriaan Rot' },
    { source: 'Alexander Kurz', target: 'Jurriaan Rot' },
    { source: 'Nick Bezhanishvili', target: 'Marcello Bonsangue' },
    { source: 'Nick Bezhanishvili', target: 'Helle Hvid Hansen' },
    { source: 'Nick Bezhanishvili', target: 'Dexter Kozen' },
    { source: 'Nick Bezhanishvili', target: 'Clemens Kupke' },
    { source: 'Nick Bezhanishvili', target: 'Prakash Panangaden' },
    { source: 'Nick Bezhanishvili', target: 'Alexandra Silva' },
    { source: 'Marcello Bonsangue', target: 'Helle Hvid Hansen' },
    { source: 'Marcello Bonsangue', target: 'Dexter Kozen' },
    { source: 'Marcello Bonsangue', target: 'Clemens Kupke' },
    { source: 'Marcello Bonsangue', target: 'Prakash Panangaden' },
    { source: 'Marcello Bonsangue', target: 'Alexandra Silva' },
    { source: 'Dexter Kozen', target: 'Clemens Kupke' },
    { source: 'Dexter Kozen', target: 'Prakash Panangaden' },
    { source: 'Dexter Kozen', target: 'Alexandra Silva' },
    { source: 'Prakash Panangaden', target: 'Alexandra Silva' },
  ],
};
