export const update_data = {
  nodes: [
    { id: 'Helle Hvid Hansen', weight: 20 },
    { id: 'Clemens Kupke', weight: 11 },
    { id: 'Jan Rutten', weight: 2 },
    { id: 'Eric Pacuit', weight: 2 },
    { id: 'Johannes Marti', weight: 4 },
    { id: 'Yde Venema', weight: 4 },
    { id: 'Jim de Groot', weight: 2 },
    { id: 'Alexander Kurz', weight: 4 },
    { id: 'Joerg Endrullis', weight: 4 },
    { id: 'Dimitri Hendriks', weight: 5 },
    { id: 'Andrew Polonsky', weight: 5 },
    { id: 'Alexandra Silva', weight: 10 },
    { id: 'Jörg Endrullis', weight: 4 },
    { id: 'Sebastian Enqvist', weight: 4 },
    { id: 'Frank M. V. Feys', weight: 1 },
    { id: 'Marcello M. Bonsangue', weight: 3 },
    { id: 'Jurriaan Rot', weight: 3 },
    { id: 'Nick Bezhanishvili', weight: 6 },
    { id: 'Marcello Bonsangue', weight: 6 },
    { id: 'Dexter Kozen', weight: 6 },
    { id: 'Prakash Panangaden', weight: 6 },
  ],
  links: [
    { source: 'Helle Hvid Hansen', target: 'Clemens Kupke' },
    { source: 'Helle Hvid Hansen', target: 'Jan Rutten' },
    { source: 'Helle Hvid Hansen', target: 'Eric Pacuit' },
    { source: 'Helle Hvid Hansen', target: 'Johannes Marti' },
    { source: 'Helle Hvid Hansen', target: 'Yde Venema' },
    { source: 'Helle Hvid Hansen', target: 'Jim de Groot' },
    { source: 'Helle Hvid Hansen', target: 'Alexander Kurz' },
    { source: 'Helle Hvid Hansen', target: 'Joerg Endrullis' },
    { source: 'Helle Hvid Hansen', target: 'Dimitri Hendriks' },
    { source: 'Helle Hvid Hansen', target: 'Andrew Polonsky' },
    { source: 'Helle Hvid Hansen', target: 'Alexandra Silva' },
    { source: 'Helle Hvid Hansen', target: 'Jörg Endrullis' },
    { source: 'Helle Hvid Hansen', target: 'Sebastian Enqvist' },
    { source: 'Helle Hvid Hansen', target: 'Frank M. V. Feys' },
    { source: 'Helle Hvid Hansen', target: 'Marcello M. Bonsangue' },
    { source: 'Helle Hvid Hansen', target: 'Jurriaan Rot' },
    { source: 'Helle Hvid Hansen', target: 'Nick Bezhanishvili' },
    { source: 'Helle Hvid Hansen', target: 'Marcello Bonsangue' },
    { source: 'Helle Hvid Hansen', target: 'Dexter Kozen' },
    { source: 'Helle Hvid Hansen', target: 'Prakash Panangaden' },
    { source: 'Clemens Kupke', target: 'Jan Rutten' },
    { source: 'Clemens Kupke', target: 'Eric Pacuit' },
    { source: 'Clemens Kupke', target: 'Johannes Marti' },
    { source: 'Clemens Kupke', target: 'Yde Venema' },
    { source: 'Clemens Kupke', target: 'Sebastian Enqvist' },
    { source: 'Clemens Kupke', target: 'Nick Bezhanishvili' },
    { source: 'Clemens Kupke', target: 'Marcello Bonsangue' },
    { source: 'Clemens Kupke', target: 'Dexter Kozen' },
    { source: 'Clemens Kupke', target: 'Prakash Panangaden' },
    { source: 'Clemens Kupke', target: 'Alexandra Silva' },
    { source: 'Johannes Marti', target: 'Yde Venema' },
    { source: 'Johannes Marti', target: 'Sebastian Enqvist' },
    { source: 'Yde Venema', target: 'Sebastian Enqvist' },
    { source: 'Jim de Groot', target: 'Alexander Kurz' },
    { source: 'Alexander Kurz', target: 'Marcello M. Bonsangue' },
    { source: 'Alexander Kurz', target: 'Jurriaan Rot' },
    { source: 'Joerg Endrullis', target: 'Dimitri Hendriks' },
    { source: 'Joerg Endrullis', target: 'Andrew Polonsky' },
    { source: 'Joerg Endrullis', target: 'Alexandra Silva' },
    { source: 'Dimitri Hendriks', target: 'Andrew Polonsky' },
    { source: 'Dimitri Hendriks', target: 'Alexandra Silva' },
    { source: 'Dimitri Hendriks', target: 'Jörg Endrullis' },
    { source: 'Andrew Polonsky', target: 'Alexandra Silva' },
    { source: 'Andrew Polonsky', target: 'Jörg Endrullis' },
    { source: 'Alexandra Silva', target: 'Jörg Endrullis' },
    { source: 'Alexandra Silva', target: 'Nick Bezhanishvili' },
    { source: 'Alexandra Silva', target: 'Marcello Bonsangue' },
    { source: 'Alexandra Silva', target: 'Dexter Kozen' },
    { source: 'Alexandra Silva', target: 'Prakash Panangaden' },
    { source: 'Marcello M. Bonsangue', target: 'Jurriaan Rot' },
    { source: 'Nick Bezhanishvili', target: 'Marcello Bonsangue' },
    { source: 'Nick Bezhanishvili', target: 'Dexter Kozen' },
    { source: 'Nick Bezhanishvili', target: 'Prakash Panangaden' },
    { source: 'Marcello Bonsangue', target: 'Dexter Kozen' },
    { source: 'Marcello Bonsangue', target: 'Prakash Panangaden' },
    { source: 'Dexter Kozen', target: 'Prakash Panangaden' },
  ],
};
